/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as SuperadminRouteImport } from './routes/superadmin'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SolicitudesRouteImport } from './routes/solicitudes'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RegisterSuccessRouteImport } from './routes/register-success'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProgramRouteImport } from './routes/program'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LevelsRouteImport } from './routes/levels'
import { Route as LessonRouteImport } from './routes/lesson'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AiLabRouteImport } from './routes/ai-lab'
import { Route as AdminUsersRouteImport } from './routes/admin-users'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReadingReadingIdRouteImport } from './routes/reading.$readingId'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminRoute = SuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SolicitudesRoute = SolicitudesRouteImport.update({
  id: '/solicitudes',
  path: '/solicitudes',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterSuccessRoute = RegisterSuccessRouteImport.update({
  id: '/register-success',
  path: '/register-success',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramRoute = ProgramRouteImport.update({
  id: '/program',
  path: '/program',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LevelsRoute = LevelsRouteImport.update({
  id: '/levels',
  path: '/levels',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonRoute = LessonRouteImport.update({
  id: '/lesson',
  path: '/lesson',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AiLabRoute = AiLabRouteImport.update({
  id: '/ai-lab',
  path: '/ai-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin-users',
  path: '/admin-users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadingReadingIdRoute = ReadingReadingIdRouteImport.update({
  id: '/reading/$readingId',
  path: '/reading/$readingId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-users': typeof AdminUsersRoute
  '/ai-lab': typeof AiLabRoute
  '/dashboard': typeof DashboardRoute
  '/lesson': typeof LessonRoute
  '/levels': typeof LevelsRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/profile': typeof ProfileRoute
  '/program': typeof ProgramRoute
  '/register': typeof RegisterRoute
  '/register-success': typeof RegisterSuccessRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/solicitudes': typeof SolicitudesRoute
  '/stats': typeof StatsRoute
  '/superadmin': typeof SuperadminRoute
  '/welcome': typeof WelcomeRoute
  '/reading/$readingId': typeof ReadingReadingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-users': typeof AdminUsersRoute
  '/ai-lab': typeof AiLabRoute
  '/dashboard': typeof DashboardRoute
  '/lesson': typeof LessonRoute
  '/levels': typeof LevelsRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/profile': typeof ProfileRoute
  '/program': typeof ProgramRoute
  '/register': typeof RegisterRoute
  '/register-success': typeof RegisterSuccessRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/solicitudes': typeof SolicitudesRoute
  '/stats': typeof StatsRoute
  '/superadmin': typeof SuperadminRoute
  '/welcome': typeof WelcomeRoute
  '/reading/$readingId': typeof ReadingReadingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-users': typeof AdminUsersRoute
  '/ai-lab': typeof AiLabRoute
  '/dashboard': typeof DashboardRoute
  '/lesson': typeof LessonRoute
  '/levels': typeof LevelsRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/profile': typeof ProfileRoute
  '/program': typeof ProgramRoute
  '/register': typeof RegisterRoute
  '/register-success': typeof RegisterSuccessRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/solicitudes': typeof SolicitudesRoute
  '/stats': typeof StatsRoute
  '/superadmin': typeof SuperadminRoute
  '/welcome': typeof WelcomeRoute
  '/reading/$readingId': typeof ReadingReadingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-users'
    | '/ai-lab'
    | '/dashboard'
    | '/lesson'
    | '/levels'
    | '/library'
    | '/login'
    | '/messages'
    | '/profile'
    | '/program'
    | '/register'
    | '/register-success'
    | '/settings'
    | '/signup'
    | '/solicitudes'
    | '/stats'
    | '/superadmin'
    | '/welcome'
    | '/reading/$readingId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-users'
    | '/ai-lab'
    | '/dashboard'
    | '/lesson'
    | '/levels'
    | '/library'
    | '/login'
    | '/messages'
    | '/profile'
    | '/program'
    | '/register'
    | '/register-success'
    | '/settings'
    | '/signup'
    | '/solicitudes'
    | '/stats'
    | '/superadmin'
    | '/welcome'
    | '/reading/$readingId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-users'
    | '/ai-lab'
    | '/dashboard'
    | '/lesson'
    | '/levels'
    | '/library'
    | '/login'
    | '/messages'
    | '/profile'
    | '/program'
    | '/register'
    | '/register-success'
    | '/settings'
    | '/signup'
    | '/solicitudes'
    | '/stats'
    | '/superadmin'
    | '/welcome'
    | '/reading/$readingId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AiLabRoute: typeof AiLabRoute
  DashboardRoute: typeof DashboardRoute
  LessonRoute: typeof LessonRoute
  LevelsRoute: typeof LevelsRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRoute
  ProfileRoute: typeof ProfileRoute
  ProgramRoute: typeof ProgramRoute
  RegisterRoute: typeof RegisterRoute
  RegisterSuccessRoute: typeof RegisterSuccessRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  SolicitudesRoute: typeof SolicitudesRoute
  StatsRoute: typeof StatsRoute
  SuperadminRoute: typeof SuperadminRoute
  WelcomeRoute: typeof WelcomeRoute
  ReadingReadingIdRoute: typeof ReadingReadingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin': {
      id: '/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof SuperadminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solicitudes': {
      id: '/solicitudes'
      path: '/solicitudes'
      fullPath: '/solicitudes'
      preLoaderRoute: typeof SolicitudesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register-success': {
      id: '/register-success'
      path: '/register-success'
      fullPath: '/register-success'
      preLoaderRoute: typeof RegisterSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program': {
      id: '/program'
      path: '/program'
      fullPath: '/program'
      preLoaderRoute: typeof ProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/levels': {
      id: '/levels'
      path: '/levels'
      fullPath: '/levels'
      preLoaderRoute: typeof LevelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson': {
      id: '/lesson'
      path: '/lesson'
      fullPath: '/lesson'
      preLoaderRoute: typeof LessonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-lab': {
      id: '/ai-lab'
      path: '/ai-lab'
      fullPath: '/ai-lab'
      preLoaderRoute: typeof AiLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-users': {
      id: '/admin-users'
      path: '/admin-users'
      fullPath: '/admin-users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reading/$readingId': {
      id: '/reading/$readingId'
      path: '/reading/$readingId'
      fullPath: '/reading/$readingId'
      preLoaderRoute: typeof ReadingReadingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdminUsersRoute: AdminUsersRoute,
  AiLabRoute: AiLabRoute,
  DashboardRoute: DashboardRoute,
  LessonRoute: LessonRoute,
  LevelsRoute: LevelsRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRoute,
  ProfileRoute: ProfileRoute,
  ProgramRoute: ProgramRoute,
  RegisterRoute: RegisterRoute,
  RegisterSuccessRoute: RegisterSuccessRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  SolicitudesRoute: SolicitudesRoute,
  StatsRoute: StatsRoute,
  SuperadminRoute: SuperadminRoute,
  WelcomeRoute: WelcomeRoute,
  ReadingReadingIdRoute: ReadingReadingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
